customimage/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import Home
from user_image.views import photo_list
from django.conf import settings
from django.conf.urls.static import static
from oauth2client.contrib.django_util import views
from django.contrib.auth.views import LoginView,LogoutView


urlpatterns = [
    path('image/',photo_list,name = 'photo'),
    # path('',include('home.urls')),
    path('oauth2callback/',views.oauth2_callback,name='callback'),
    path('home/',include('home.urls')),
    path('oauth2authorize/',views.oauth2_authorize,name='authorize'),
    path('',Home.as_view(),name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    # path('', include(('django.contrib.auth.urls','auth'), namespace='auth')),
]


# urlpatterns = (urlpatterns, "google_oauth", "google_oauth")

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import Event_Create,Event_delete,Event_list

app_name = 'event'

urlpatterns = [
    path('list/',Event_list.as_view(),name = 'list'),
    path('create/',Event_Create.as_view(),name = 'event_create'),
    path('delete/<pk>',Event_delete.as_view(),name = 'delete')
] 

user_image/urls.py
from django.urls import path


urls_patterns = [
    
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from oauth2client.contrib.django_util.models import CredentialsField
from django.dispatch import receiver
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User,unique=True, null=False, db_index=True,on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)



class Event(models.Model):
    user = models.ForeignKey(User ,null=True ,blank=True, on_delete= models.CASCADE)
    name = models.CharField(max_length = 234,null = False , blank = 'false')
    starttime = models.DateTimeField()
    endtime = models.DateTimeField()
    unique_id = models.CharField(null = True , blank = True , max_length = 232)


    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse('home')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)



@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

user_image/models.py
from django.db import models

# Create your models here.
class Photo(models.Model):
    file  = models.ImageField()
    upload_at  = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'


        

home/forms.py
from django.shortcuts import redirect, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from home.models import Profile
from django import forms
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio','location','birth_date')

user_image/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo

class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

customimage/views.py
from django.views.generic import TemplateView
from oauth2client.contrib.django_util import oauth2_settings

class Home(TemplateView):
    template_name = 'base.html'

home/views.py
from .utils import add_event , delete_event
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic.list import ListView
from django.urls import reverse , reverse_lazy
from .models import Event 
from django.views.generic.edit import CreateView , DeleteView


def Logout(request):
    logout(request)
    return HttpResponseRedirect('/')



class Event_Create(SuccessMessageMixin,CreateView):
    model = Event
    fields = ['name','starttime','endtime']
    template_name = 'home/create_event.html'
    success_message = 'Your Event is Created'

    def form_valid(self , form):
        form.instance.user = self.request.user
        startime = form.cleaned_data['starttime']
        print(startime)
        endtime = form.cleaned_data['endtime']
        print(endtime)
        name = form.cleaned_data['name']
        print(name)
        a = add_event(startime = startime , endtime = endtime , name = name )
        form.instance.unique_id = a
        return super(Event_Create,self).form_valid(form)

    def get_success_url(self , **kwargs):
        super(Event_Create,self).get_success_url(**kwargs)
        success_url = reverse('event:list')
        return success_url    


class Event_delete(SuccessMessageMixin , DeleteView):
    model = Event
    success_url = reverse_lazy('home')
    success_message = "Event is Delete succesfully"
    template_name = 'home/event_delete.html'


    def get_queryset(self ,**kwargs):
        queryset = super(Event_delete ,self).get_queryset(**kwargs)
        q = Event.objects.get(pk = self.kwargs.get('pk'))
        # print(q.unique_id)
        # delete_event(delete_id = q.unique_id)
        return queryset.filter(pk=self.kwargs.get('pk'))

     

    def post(self, request , *args , **kwargs):
        q = Event.objects.get(pk = self.kwargs.get('pk'))
        print(q.unique_id)
        delete_event(delete_id = q.unique_id)
        return self.delete(request, *args, **kwargs)




class Event_list(ListView):
    model = Event
    template_name = 'home/event_list.html'

user_image/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from django.shortcuts import render, redirect

from .models import Photo
from .forms import PhotoForm

# Create your views here.


class Home(TemplateView): 
    template_name = 'image/home.html'
    


def photo_list(request):
    photos = Photo.objects.all()
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('photo')
    else:
        form = PhotoForm()
    return render(request, 'album/photo_list.html', {'form': form, 'photos': photos})    

templates/album/photo_list.html
{% extends 'base.html' %}

{% block javascript %}
<script>
    $(function () {

        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
        $("#id_file").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1 / 1,
                minCropBoxWidth: 25,
                minCropBoxHeight: 25,
                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
        });

        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });


        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            console.log(cropData)
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
        });

    });
</script>
{% endblock %}

{% block content %}
<h1 class="page-header">Album</h1>

<!-- FORM TO UPLOAD THE IMAGES -->
<form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
</form>

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
                <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                    <button type="button" class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"><i class="fas fa-search-plus"></i></span>
                    </button>
                    <button type="button" class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"><i class="fas fa-search-minus"></i></span>
                    </button>
                    <input type="heigth" value="" placeholder="Height" id ="height" style="height:2%;width: 20%;" type="number">
                    <input type="width" value="" placeholder="width", id="width"  style="height:2%;width: 20%;" type="number">
                </div>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-ban"></i></button>
                <button type="button" class="btn btn-primary js-crop-and-upload"><i class="fas fa-file-upload"></i></button>
            </div>
        </div>
    </div>
</div>

<!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
<div class="row" style="margin-top: 20px">
    {% for photo in photos %}
    <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail" style="padding:5%;">
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css">

    <title>Hello, world!</title>
</head>

<body>
    {% include 'navbar.html'%}
    <div class="alert alert-success">
        {% if messages %}
                {% for message in messages %}
                <h3 {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</h3>
                {% endfor %}
        {% endif %}
    </div>

    {% if user.is_authenticated %}
        <h2>Hi <i class="far fa-smile"></i> {{user.username}}</h2>
    {%endif%}    
    <div class="container">
    {%block content%}


    {%endblock%}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js"></script>
    {%block javascript%}
    {%endblock%}    
</body>

</html>

templates/home/create_event.html
{%extends 'base.html'%}
{%block content%}
<form method="post" action="{% url 'event:event_create' %}">{% csrf_token %}
    <div class="form-group">
        <label for="id_name">Event Name:</label> 
        <input type="text" name="name" maxlength="234" class="form-control" id="id_name">
        <label for="id_starttime">Starttime: Your format should be like "%Y-%M-%D %H:%M:%S"</label> 
        <input type="text" name="starttime" required="required" class="form-control" id="id_starttime">

        <label for="id_endtime">Endtime:Your format should be like "%Y-%M-%D %H:%M:%S"</label> 
        <input type="text" name="endtime" required="required" class="form-control" id="id_endtime">
        <input type="submit" class="btn btn-primary" style="margin-top:5px;" value="Save">
    </div>    
</form>
{%endblock%}

templates/home/event_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/home/event_list.html
{%extends 'base.html'%}
{%block content %}
<div class="alert alert-success">
    {% if messages %}
    <ul class="">
        <p>
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </p>
    </ul>
    {% endif %}
</div>

<h2>Your Event </h2>
{%if object_list %}
{% for object in object_list %}      
<ul>
<li><h3>{{object.name}}</h3>
        <a href="{% url 'event:delete' pk=object.pk %}">
            <p><button class="btn btn-danger">Delete</button></p>
        </a></li>
{%endfor%}
{% else %}
<h3> NO Event Create. Create One Now </h3><a href="{% url 'event:list'%}"><button class="btn btn-success">Create</button></a>
{%endif%}
{%endblock%}

templates/home/home.html
{% extends 'home/base.html' %}
{% block content %}
<div class="row">
    <div class="col s12 m6 offset-m3">
        <H3>Hi {{ user.email }}!</H3>
    </div>
</div>
{% endblock %}

templates/home/profile.html
{% extends ‘home/base.html’ %}
{% block content %}
<div class=”row”>
    <div class=”col s12 m6 offset-m3">
        <H3>Hi {{ user.email }}!</H3>
    </div>
</div>
<form method=”post”>
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type=”submit”>Save changes</button>
</form>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout'%}">Logout<span class="sr-only">(current)</span></a>
                <li class="nav-item active"> <a class="nav-link" href="{% url 'event:event_create'%}">Create Event<span class="sr-only">(current)</span></a></li>
                <li class="nav-item active"> <a class="nav-link" href="{% url 'event:list'%}">Your Event<span class="sr-only">(current)</span></a></li>
                {%else%}
                <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
                {%endif%}
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'photo'%}">Edit photo</a>
            </li>
        </ul>
    </div>
</nav>